=== EclipseETS/eclipse-telemetry/EclipseTelemetry/protocolV7Schema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio - FREE Community Edition 7.0.5.906 (http://www.liquid-technologies.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://eclipse.etsmtl.ca" xmlns="http://eclipse.etsmtl.ca"
	elementFormDefault="qualified">
	<xs:complexType name="definitionsBitsOff">
		<xs:sequence>
			<xs:element name="definition" type="xs:string" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="definitionsBitsOn">
		<xs:sequence>
			<xs:element name="definition" type="xs:string" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="deviceitem">
		<xs:sequence>
			<xs:element name="unit" type="xs:string" />
			<xs:element name="minvalue" type="xs:integer" />
			<xs:element name="maxvalue" type="xs:integer" />
			<xs:element name="status" type="xs:integer" />
			<xs:element name="resolution" type="xs:double" />
			<xs:element name="factor" type="xs:double" />
			<xs:element name="offset" type="xs:integer" />
			<xs:element name="range" type="xs:integer" />
			<xs:element name="numbits" type="xs:integer" />
			<xs:element name="signed" type="xs:boolean" />
			<xs:element name="isFloat" type="xs:boolean" />
			<xs:element minOccurs="0" name="definitionsBitsOff" type="definitionsBitsOn" />
			<xs:element minOccurs="0" name="definitionsBitsOn" type="definitionsBitsOff" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" />
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="device">
		<xs:sequence>
			<xs:element name="deviceitem" type="deviceitem" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" />
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>
	<xs:element name="devices">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="device" type="device" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EclipseETS/eclipse-telemetry/EclipseTelemetry/protocolV7.xml
<?xml version="1.0" encoding="UTF-8" ?>

<devices xmlns="http://eclipse.etsmtl.ca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	xsi:schemaLocation="http://eclipse.etsmtl.ca protocolV7Schema.xsd">

<!-- DRIVE -->

<device id="4" name="Drive">
	<deviceitem id="0" name="CMD_Current">
		<unit>%</unit>
		<minvalue>0</minvalue>
		<maxvalue>65532</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="1" name="CMD_MotorVelocity">
		<unit>m/s</unit>
		<minvalue>0</minvalue>
		<maxvalue>65532</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="2" name="CMD_BusCurrent">
		<unit>%</unit>
		<minvalue>0</minvalue>
		<maxvalue>65532</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="3" name="ErrorFlags">
		<unit>Bin</unit>
		<minvalue>0</minvalue>
		<maxvalue>65532</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="4" name="LimitFlags">
		<unit>Bin</unit>
		<minvalue>0</minvalue>
		<maxvalue>65532</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="5" name="BusCurrent">
		<unit>A</unit>
		<minvalue>-120</minvalue>
		<maxvalue>120</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="6" name="BusVoltage">
		<unit>V</unit>
		<minvalue>91</minvalue>
		<maxvalue>133</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="7" name="VehicleVelocity">
		<unit>Km/h</unit>
		<minvalue>0</minvalue>
		<maxvalue>30</maxvalue>
		<status>1</status>
		<resolution>3.6</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="8" name="MotorVelocity">
		<unit>rpm</unit>
		<minvalue>0</minvalue>
		<maxvalue>65535</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="23" name="HeatSinkTemp">
		<unit>C</unit>
		<minvalue>-100</minvalue>
		<maxvalue>100</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="24" name="MotorTemp">
		<unit>C</unit>
		<minvalue>-100</minvalue>
		<maxvalue>100</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="25" name="AirInletTemp">
		<unit>C</unit>
		<minvalue>-100</minvalue>
		<maxvalue>100</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="26" name="ProcessorTemp">
		<unit>C</unit>
		<minvalue>-100</minvalue>
		<maxvalue>100</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="29" name="DCBusAmpHours">
		<unit>Ah</unit>
		<minvalue>0</minvalue>
		<maxvalue>200</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
	<deviceitem id="30" name="Odometer">
		<unit>m</unit>
		<minvalue>0</minvalue>
		<maxvalue>4000000</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>true</isFloat>
	</deviceitem>
</device>

<!-- VOLANT -->

<device id="6" name="Volant">
	<deviceitem id="1" name="Status">
		<unit>Bin</unit>
		<minvalue>0</minvalue>
		<maxvalue>65535</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>8</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="2" name="Bouton">
		<unit>Bin</unit>
		<minvalue>0</minvalue>
		<maxvalue>256</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>8</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="4" name="Pot">
		<unit>Bin</unit>
		<minvalue>-128</minvalue>
		<maxvalue>127</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>8</numbits>
		<signed>true</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="5" name="Velocity">
		<unit>m/s</unit>
		<minvalue>0</minvalue>
		<maxvalue>30</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>32</numbits>
		<signed>true</signed>
		<isFloat>false</isFloat>
	</deviceitem>
</device>

<!-- DASH -->

<device id="7" name="Dash">
	<deviceitem id="1" name="Status">
		<unit>Bin</unit>
		<minvalue>0</minvalue>
		<maxvalue>65535</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>8</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="2" name="PedalPot">
		<unit>Bin</unit>
		<minvalue>0</minvalue>
		<maxvalue>256</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>8</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="3" name="Bouton">
		<unit>Bin</unit>
		<minvalue>0</minvalue>
		<maxvalue>256</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>8</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
</device>

<!-- STARTUPCTRL -->

<device id="8" name="StartupCtrl">
	<deviceitem id="1" name="Status">
		<unit>Bin</unit>
		<minvalue>0</minvalue>
		<maxvalue>65535</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>16</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="2" name="PcMPPT">
		<unit>V</unit>
		<minvalue>0</minvalue>
		<maxvalue>0</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>16</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="3" name="PcDrive">
		<unit>V</unit>
		<minvalue>0</minvalue>
		<maxvalue>0</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>16</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="4" name="Courant15">
		<unit>A</unit>
		<minvalue>-120</minvalue>
		<maxvalue>120</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>16</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="5" name="Tension15">
		<unit>V</unit>
		<minvalue>-130</minvalue>
		<maxvalue>130</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>16</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="6" name="Courant10">
		<unit>A</unit>
		<minvalue>-120</minvalue>
		<maxvalue>120</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>16</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="7" name="Tension10">
		<unit>V</unit>
		<minvalue>-130</minvalue>
		<maxvalue>130</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>16</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="8" name="LemBatt1">
		<unit>A</unit>
		<minvalue>-120</minvalue>
		<maxvalue>120</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
		<numbits>16</numbits>
		<signed>false</signed>
		<isFloat>false</isFloat>
	</deviceitem>
	<deviceitem id="9" name="LemMPPT">
		<unit>A</unit>
		<minvalue>-120</minvalue>
		<maxvalue>120</maxvalue>
		<status>1</status>
		<resolution>1</resolution>
		<factor>1</factor>
		<offset>0</offset>
		<range>0</range>
